project_id = "cbdaidsvljaoysbtxfrb"

[functions.invite-admin]
verify_jwt = false

[functions.list-admins]
verify_jwt = false

[functions.remove-admin]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.notify-curriculum-lead]
verify_jwt = false

[functions.portal-auto-login]
verify_jwt = false
